name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0 libnotify-dev libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libdrm2 libgbm1 libxcb-dri3-0 libxkbcommon0 libgtk-3-0
          
      - name: Install dependencies
        run: pnpm install --shamefully-hoist
        
      - name: Build app
        run: pnpm run build
        
      - name: Package app (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          export ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
          pnpm exec electron-builder --mac --config.publish=null
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          
      - name: Package app (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          set ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
          pnpm exec electron-builder --win --config.publish=null
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          
      - name: Package app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
          pnpm exec electron-builder --linux --config.publish=null
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
            dist/*.blockmap
            dist/*-mac.zip
            
  create-release:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          
      - name: List artifacts
        run: |
          echo "Downloaded artifacts:"
          find dist -type f -name "*" | head -20
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.dmg
            dist/**/*.exe
            dist/**/*.AppImage
            dist/**/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}